config/routes.rb
Md::Application.routes.draw do

  resources :dashboards

  

  devise_for :users

  match "/patients/search", :controller => "patients", :action => "search", :via => :get

  resources :patients do
    match 'timeline' => "patients#timeline", :action => 'timeline', :via => :get
    get :autocomplete_patients_last_name, :on => :collection

    resources :allergies do
      get :autocomplete_allergies_name, :on => :collection
      resources :attachments
    end
    resources :immunizations do
      get :autocomplete_immunizations_name, :on => :collection
      resources :attachments
    end
    resources :surgeries do
      get :autocomplete_surgeries_name, :on => :collection
      resources :attachments
    end
    resources :imagings do
      get :autocomplete_imagings_name, :on => :collection
      resources :attachments
    end
    resources :medications do
      get :autocomplete_medications_name, :on => :collection
      get :autocomplete_medications_med_type, :on => :collection
      get :autocomplete_medications_dose_unit, :on => :collection
      resources :attachments
    end
    resources :vitals do
      get :autocomplete_vitals_name, :on => :collection
      get :autocomplete_vitals_vital_unit, :on => :collection
      resources :attachments 
    end

  end

  match "/uploads/:id/:filename.:extension", :controller => "attachments", :action => "download", :constraints => { :filename => /[^\/]+/ },  :conditions => { :method => :get }

  root :to => 'dashboards#index'

end

app/models/medication.rb
class Medication < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :patient
  has_many :attachments, :dependent => :destroy
  validates :dose, :numericality => true

  accepts_nested_attributes_for :attachments, :reject_if => lambda { |c| c[:attachment].blank? }
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController

  before_filter :authenticate_user!
  # autocomplete :medications, :name, :class_name => Medication
  # autocomplete :medications, :med_type, :class_name => Medication
  # autocomplete :medications, :dose_unit, :class_name => Medication

  def autocomplete_medications_name
    term = params[:term]
    if term && !term.empty?
        items = Medication.select("distinct name").
            where("LOWER(name) like ?", '%'+term.downcase + '%').
            limit(10).order(:name)
     else
       items = {}
     end
     render :json => json_for_autocomplete(items, :name)
  end

  def autocomplete_medications_med_type
    term = params[:term]
    if term && !term.empty?
        items = Vital.select("distinct med_type").
            where("LOWER(med_type) like ?", '%'+term.downcase + '%').
            limit(10).order(:med_type)
     else
       items = {}
     end
     render :json => json_for_autocomplete(items, :med_type)
  end

  def autocomplete_medications_dose_unit
    term = params[:term]
    if term && !term.empty?
        items = Vital.select("distinct dose_unit").
            where("LOWER(dose_unit) like ?", '%'+term.downcase + '%').
            limit(10).order(:dose_unit)
     else
       items = {}
     end
     render :json => json_for_autocomplete(items, :dose_unit)
  end

  # GET /medications
  # GET /medications.json
  def index
    # @medications = Medication.all
    @patient = Patient.find(params[:patient_id])
    @medications = Medication.find_all_by_patient_id(params[:patient_id])

    @page_title = @patient.full_name
    @page_desc = "Viewing medications"

    if can? :manage, @patient
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @medications }
      end

    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # GET /medications/1
  # GET /medications/1.json
  def show
    # @medication = Medication.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @medication = @patient.medications.find(params[:id])

    @page_title = @patient.full_name
    @page_desc = "Viewing medication"

    if can? :manage, @patient
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @medication }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # GET /medications/new
  # GET /medications/new.json
  def new
    # @medication = Medication.new
    @patient = Patient.find(params[:patient_id])
    @medication = @patient.medications.new

    @page_title = @patient.full_name
    @page_desc = "Adding a new medication"

    if can? :manage, @patient
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @medication }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # GET /medications/1/edit
  def edit
    # @medication = Medication.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @medication = @patient.medications.find(params[:id])

    @page_title = @patient.full_name
    @page_desc = "Editing a new medication"

    if can? :manage, @patient
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # POST /medications
  # POST /medications.json
  def create
    # @medication = Medication.new(params[:medication])
    @patient = Patient.find(params[:patient_id])
    @medication = @patient.medications.build(params[:medication])

    if can? :manage, @patient
      respond_to do |format|
        if @medication.save
          format.html { redirect_to patient_medications_url(params[:patient_id]), notice: 'Medication was successfully created.'  }
          format.json { render json: @medication, status: :created, location: @medication }
        else
          format.html { render action: "new" }
          format.json { render json: @medication.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # PUT /medications/1
  # PUT /medications/1.json
  def update
    # @medication = Medication.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @medication = @patient.medications.find(params[:id])

    if can? :manage, @patient
      respond_to do |format|
        if @medication.update_attributes(params[:medication])
          format.html { redirect_to patient_medications_url(params[:patient_id]), notice: 'Medication was successfully updated.'  }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @medication.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # DELETE /medications/1
  # DELETE /medications/1.json
  def destroy
    # @medication = Medication.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @medication = Medication.find(params[:id])

    if can? :manage, @patient
      @medication.destroy

      respond_to do |format|
        format.html { redirect_to patient_medications_url(params[:patient_id]), notice: 'Medication was successfully deleted.'  }
        format.json { head :ok }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_fields.html.erb
<% if @medication.errors.any? %>
  <div id="error_explanation" class="alert alert-error" > 
    <a class="close" data-dismiss="alert" href="#">&times;</a>
    <b><%= pluralize(@medication.errors.count, "error") %> prohibited this medication from being saved:</b>

    <ul>
    <% @medication.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="control-group">
  <%= f.label :name, :class=>'control-label' %>
  <div class="controls">
    <%= f.autocomplete_field :name, autocomplete_medications_name_patient_medications_path, :class => 'xlarge' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :desc, :class=>'control-label' %>
  <div class="controls">
    <%= f.text_area :desc, :class=> 'xlarge',  :rows => '4' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :started_on, :class=>'control-label' %>
  <div class="controls">
    <%= f.text_field :started_on, :class => 'xlarge' %>
    <span class="help-block">(format: YYYY-MM-DD)</span>
  </div>
</div>

<div class="control-group">
  <%= f.label :ended_on, :class=>'control-label' %>
  <div class="controls">
    <%= f.text_field :ended_on, :class => 'xlarge' %>
    <span class="help-block">(format: YYYY-MM-DD)</span>
  </div>
</div>
<div class="control-group">
  <%= f.label :med_type, :class=>'control-label' %>
  <div class="controls">
    <%= f.autocomplete_field :med_type, autocomplete_medications_med_type_patient_medications_path, :class => 'xlarge' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :dose, :class=>'control-label' %>
  <div class="controls">
    <%= f.text_field :dose %>
  </div>
</div>
<div class="control-group">
  <%= f.label :dose_unit, :class=>'control-label' %>
  <div class="controls">
    <%= f.autocomplete_field :dose_unit, autocomplete_medications_dose_unit_patient_medications_path, :class => 'xlarge' %>
  </div>
</div>

<%= f.fields_for :attachments do |attachment_form|  %>
  <div class="control-group">
    <%= attachment_form.label :attachment, :class=>'control-label' %>
    <div class="controls">
      <%= attachment_form.file_field :attachment %>
      <%= attachment_form.link_to_remove "Remove this attachment" %>
    </div>
  </div>
  <% end %> 

  <%= f.link_to_add "Add attachment", :attachments, :class=>'btn btn-mini btn-info add_attachment_link_button' %>

  <div class="actions form-actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
</fieldset>

app/views/medications/_form.html.erb
<%= form_for(@medication) do |f| %>
  <% if @medication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medication.errors.count, "error") %> prohibited this medication from being saved:</h2>

      <ul>
      <% @medication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :started_on %><br />
    <%= f.date_select :started_on %>
  </div>
  <div class="field">
    <%= f.label :ended_on %><br />
    <%= f.date_select :ended_on %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_area :type %>
  </div>
  <div class="field">
    <%= f.label :type_others %><br />
    <%= f.text_area :type_others %>
  </div>
  <div class="field">
    <%= f.label :dose %><br />
    <%= f.text_field :dose %>
  </div>
  <div class="field">
    <%= f.label :dose_unit %><br />
    <%= f.text_field :dose_unit %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br />
    <%= f.number_field :patient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medications/edit.html.erb
<%= nested_form_for [@patient, @medication], :html => {:multipart => true, :class=>'form-horizontal'} do |f| %> 
    <%= render :partial => "fields", :locals => {:f => f} %>
<% end %>

app/views/medications/index.html.erb
<table class="table table-striped table-bordered">
  <% if @medications.empty? %>
  <tr>
    <td>
      <span id="no_record">No record.</span>
    </td>
  </tr>
  <% end %>
<% @patient.medications.each do |medication| %>
  <tr>
    <td>
      <h3><%= medication.name %></h3> <i><%= medication.desc %></i>
      <%= medication.dose %> <%= medication.dose_unit %> <%= medication.med_type %>
    </td>
    <td>
      Started on: <%= medication.started_on %>
    </td>
    <td>
      Ended on: <%= medication.ended_on %>
    </td>
    <td>
      <%= link_to 'Edit', edit_patient_medication_path(medication.patient_id, medication), :class => 'btn btn-info btn-mini' %> 
      <%= link_to 'Remove', patient_medication_path(@patient.id, medication), :class => 'btn btn-danger btn-mini',confirm: 'Are you sure?', method: :delete %>
      <%= link_to 'Add Attachment', new_patient_medication_attachment_path(medication.patient_id, medication.id), :class => 'btn btn-success btn-mini' %>
    </td>
    <% medication.attachments.each do |attachment| %>
    <tr>
      <td>
        <%= link_to File.basename(attachment.attachment.url), "/uploads/#{attachment.id}/#{File.basename(attachment.attachment.url)}" %>
      </td>
      <td colspan="3">
        <%= link_to 'Delete', patient_medication_attachment_path(medication.patient_id, medication, attachment),:class => 'btn btn-danger btn-mini' ,confirm: 'Are you sure?', method: :delete %>
      </td>
    </tr>
    <% end %>
    <tr>
    <td colspan="4">
      &nbsp;
    </td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Medication', new_patient_medication_path %>

app/views/medications/new.html.erb
<%= nested_form_for [@patient, @medication], :html => {:multipart => true, :class=>'form-horizontal'} do |f| %> 
    <%= render :partial => "fields", :locals => {:f => f} %>
<% end %>

app/views/medications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @medication.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @medication.desc %>
</p>

<p>
  <b>Started on:</b>
  <%= @medication.started_on %>
</p>

<p>
  <b>Ended on:</b>
  <%= @medication.ended_on %>
</p>

<p>
  <b>Type:</b>
  <%= @medication.med_type %>
</p>

<p>
  <b>Type others:</b>
  <%= @medication.type_others %>
</p>

<p>
  <b>Dose:</b>
  <%= @medication.dose %>
</p>

<p>
  <b>Dose unit:</b>
  <%= @medication.dose_unit %>
</p>

<p>
  <b>Patient:</b>
  <%= @medication.patient_id %>
</p>


<%= link_to 'Edit', edit_patient_medication_path(@medication, :patient_id => @medication.patient_id) %> |
<%= link_to 'Back', patient_path(@medication.patient_id) %>