config/routes.rb
Md::Application.routes.draw do

  resources :dashboards

  

  devise_for :users

  match "/patients/search", :controller => "patients", :action => "search", :via => :get

  resources :patients do
    match 'timeline' => "patients#timeline", :action => 'timeline', :via => :get
    get :autocomplete_patients_last_name, :on => :collection

    resources :allergies do
      get :autocomplete_allergies_name, :on => :collection
      resources :attachments
    end
    resources :immunizations do
      get :autocomplete_immunizations_name, :on => :collection
      resources :attachments
    end
    resources :surgeries do
      get :autocomplete_surgeries_name, :on => :collection
      resources :attachments
    end
    resources :imagings do
      get :autocomplete_imagings_name, :on => :collection
      resources :attachments
    end
    resources :medications do
      get :autocomplete_medications_name, :on => :collection
      get :autocomplete_medications_med_type, :on => :collection
      get :autocomplete_medications_dose_unit, :on => :collection
      resources :attachments
    end
    resources :vitals do
      get :autocomplete_vitals_name, :on => :collection
      get :autocomplete_vitals_vital_unit, :on => :collection
      resources :attachments 
    end

  end

  match "/uploads/:id/:filename.:extension", :controller => "attachments", :action => "download", :constraints => { :filename => /[^\/]+/ },  :conditions => { :method => :get }

  root :to => 'dashboards#index'

end

app/models/vital.rb
class Vital < ActiveRecord::Base
  validate :vital_date_is_date
  validates :name, :presence => true
  validates :vital_value, :numericality => true
  belongs_to :patient
  has_many :attachments, :dependent => :destroy

  accepts_nested_attributes_for :attachments,:reject_if => lambda { |c| c[:attachment].blank? }

  # scope :unique_name, group(:name)
  # scope :unique_vital_unit, group(:vital_unit)

  private

  def vital_date_is_date
    # Rails.logger.info ("EEEEEEEEEEEEEEEEE "+vital_date.to_yaml)
    if !vital_date.is_a?(Date)
      errors.add(:vital_date, 'must be a valid date')
    end

  end
end

app/controllers/vitals_controller.rb
class VitalsController < ApplicationController


  before_filter :authenticate_user!
  # autocomplete :vitals, :name, :scopes => [:unique_name], :full => true ,:class_name => Vital
  # autocomplete :vitals, :vital_unit,  :scopes => [:unique_vital_unit], :full => true, :class_name => Vital

  def autocomplete_vitals_name
    term = params[:term]
    if term && !term.empty?
        items = Vital.select("distinct name").
            where("LOWER(name) like ?", '%'+term.downcase + '%').
            limit(10).order(:name)
     else
       items = {}
     end
     render :json => json_for_autocomplete(items, :name)
  end

  def autocomplete_vitals_vital_unit
    term = params[:term]
    if term && !term.empty?
        items = Vital.select("distinct vital_unit").
            where("LOWER(vital_unit) like ?", '%'+term.downcase + '%').
            limit(10).order(:vital_unit)
     else
       items = {}
     end
     render :json => json_for_autocomplete(items, :vital_unit)
  end

  # GET /vitals
  # GET /vitals.json
  def index
    # @vitals = Vital.all
    @patient = Patient.find(params[:patient_id])
    @vitals = Vital.find_all_by_patient_id(params[:patient_id])

    @page_title = @patient.full_name
    @page_desc = "Viewing vitals"

    if can? :manage, @patient
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @vitals }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # GET /vitals/1
  # GET /vitals/1.json
  def show
    # @vital = Vital.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @vital = @patient.vitals.find(params[:id])

    @page_title = @patient.full_name
    @page_desc = "Viewing a vital"

    if can? :manage, @patient
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @vital }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # GET /vitals/new
  # GET /vitals/new.json
  def new
    # @vital = Vital.new
    @patient = Patient.find(params[:patient_id])
    @vital = @patient.vitals.new

    @page_title = @patient.full_name
    @page_desc = "Adding a new vital"

    if can? :manage, @patient
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @vital }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # GET /vitals/1/edit
  def edit
    # @vital = Vital.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @vital = @patient.vitals.find(params[:id])

    @page_title = @patient.full_name
    @page_desc = "Editing a vital"

    if can? :manage, @patient
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # POST /vitals
  # POST /vitals.json
  def create
    # @vital = Vital.new(params[:vital])
    @patient = Patient.find(params[:patient_id])
    @vital = @patient.vitals.build(params[:vital])

    # if @vital = @patient.vitals.create(params[:vital])
    #   # success
    # else
    #   # error handling
    # end

    if can? :manage, @patient
      respond_to do |format|
        if @vital.save
          format.html { redirect_to patient_vitals_url(params[:patient_id]), notice: 'Vital was successfully created.'  }
          format.json { render json: @vital, status: :created, location: @vital }
        else
          format.html { render action: "new" }
          format.json { render json: @vital.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # PUT /vitals/1
  # PUT /vitals/1.json
  def update
    # @vital = Vital.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @vital = @patient.vitals.find(params[:id])

    if can? :manage, @patient
      respond_to do |format|
        if @vital.update_attributes(params[:vital])
          format.html { redirect_to patient_vitals_url(params[:patient_id]), notice: 'Vital was successfully updated.'  }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @vital.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # DELETE /vitals/1
  # DELETE /vitals/1.json
  def destroy
    # @vital = Vital.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @vital = Vital.find(params[:id])

    if can? :manage, @patient
      @vital.destroy

      respond_to do |format|
        format.html { redirect_to patient_vitals_url(params[:patient_id]), notice: 'Vital was successfully deleted.'  }
        format.json { head :ok }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/vitals/_fields.html.erb
<fieldset>
  <legend><%= @page_desc %></legend>
  <% if @vital.errors.any? %>
    <div id="error_explanation" class="alert alert-error" > 
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <b><%= pluralize(@vital.errors.count, "error") %> prohibited this vital from being saved:</b>

      <ul>
      <% @vital.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class=>'control-label' %>
    <div class="controls">
      <%= f.autocomplete_field :name, autocomplete_vitals_name_patient_vitals_path, :class => 'xlarge' %>
      <span class="help-block">Ex: Weight, Height</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :vital_value, :class=>'control-label' %>
    <div class="controls">
      <%= f.text_field :vital_value, :class => 'xlarge' %> <span class="help-block">Ex: 70, 87.2, 80</span>
    </div>  
  </div>

  <div class="control-group">
    <%= f.label :vital_unit, :class=>'control-label'%>
    <div class="controls">
      <%= f.autocomplete_field :vital_unit, autocomplete_vitals_vital_unit_patient_vitals_path, :distinct => true,  :class => 'xlarge' %>
      <span class="help-block">Ex: Kilograms, Meters, Centimeters</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :desc, :class=>'control-label' %>
    <div class="controls">
      <%= f.text_area :desc, :class=> 'xlarge',  :rows => '4' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :vital_date, :class=>'control-label' %>
    <div class="controls">
      <%= f.text_field :vital_date, :class => 'xlarge' %>
      <span class="help-block">(format: YYYY-MM-DD)</span>
    </div>
  </div>
  
  <%= f.fields_for :attachments do |attachment_form|  %>
  <div class="control-group">
    <%= attachment_form.label :attachment, :class=>'control-label' %>
    <div class="controls">
      <%= attachment_form.file_field :attachment %>
      <%= attachment_form.link_to_remove "Remove this attachment" %>
    </div>
  </div>
  <% end %> 
  <%= f.link_to_add "Add attachment", :attachments, :class=>'btn btn-mini btn-info add_attachment_link_button' %>

  <div class="actions form-actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
</fieldset>

app/views/vitals/_form.html.erb
<%= form_for(@vital) do |f| %>
  <% if @vital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vital.errors.count, "error") %> prohibited this vital from being saved:</h2>

      <ul>
      <% @vital.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :vital_value %><br />
    <%= f.text_field :vital_value %>
  </div>
  <div class="field">
    <%= f.label :vital_unit %><br />
    <%= f.text_field :vital_unit %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br />
    <%= f.number_field :patient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vitals/edit.html.erb
<%= nested_form_for [@patient, @vital], :html => {:multipart => true, :class=>'form-horizontal'} do |f| %> 
    <%= render :partial => "fields", :locals => {:f => f} %>
<% end %>

app/views/vitals/index.html.erb
<table class="table table-striped table-bordered">
  
  <% if @vitals.empty? %>
  <tr>
    <td>
      <span id="no_record">No record.</span>
    </td>
  </tr>
  <% else %>

    <% @vitals.each do |vital| %>
      <tr>
        <td>
          <h3><%= vital.name %>: <%= vital.vital_value %> <%= vital.vital_unit %></h3> <i><%= vital.desc %></i>

          <% if vital.attachments %>
            <ul class="attachments_list">
            <% vital.attachments.each do |attachment| %>
              <li>
                <% if attachment.attachment.thumb_100x100.url && FileTest.exists?(attachment.attachment.thumb_100x100.url) %>
                  <a href="/uploads/<%= attachment.id %>/<%= File.basename(attachment.attachment.url) %>"><img src="/uploads/<%= attachment.id %>/<%= File.basename(attachment.attachment.thumb_100x100.url) %>"/></a>
                    
                <% else %>
                   <a href="/uploads/<%= attachment.id %>/<%= File.basename(attachment.attachment.url) %>"><%= File.basename(attachment.attachment.url) %></a>
                <% end %>
                <br/>
                <%= link_to 'Delete', patient_vital_attachment_path(vital.patient_id, vital, attachment), :class => 'btn btn-mini',confirm: 'Are you sure you want to delete "'+File.basename(attachment.attachment.url) +'" ?', method: :delete %>
              </li>
            <% end %>
            </ul>
          <% end %>
        </td>
        <td>
          <%= link_to 'Edit', edit_patient_vital_path(vital.patient_id, vital), :class => 'btn btn-info btn-mini' %> 
          <%= link_to 'Remove', patient_vital_path(vital.patient_id, vital), :class => 'btn btn-danger btn-mini',confirm: 'Are you sure?', method: :delete %>
          <%= link_to 'Add Attachment', new_patient_vital_attachment_path(vital.patient_id, vital.id), :class => 'btn btn-success btn-mini' %>
        </td>
      </tr>
      
      <tr>
        <td colspan="2">
          &nbsp;
        </td>
      </tr>
    <% end %>
  <% end %>   
</table>

<br />
<%= link_to 'New Vital', new_patient_vital_path %>

app/views/vitals/new.html.erb
<%= nested_form_for [@patient, @vital], :html => {:multipart => true, :class=>'form-horizontal'} do |f| %> 
    <%= render :partial => "fields", :locals => {:f => f} %>
<% end %>

<%= link_to 'Back', patient_path(params[:patient_id]) %>

app/views/vitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @vital.name %>
</p>

<p>
  <b>Vital value:</b>
  <%= @vital.vital_value %>
</p>

<p>
  <b>Vital unit:</b>
  <%= @vital.vital_unit %>
</p>

<p>
  <b>Desc:</b>
  <%= @vital.desc %>
</p>

<p>
  <b>Patient:</b>
  <%= @vital.patient_id %>
</p>


<%= link_to 'Edit', edit_patient_vital_path(@vital, :patient_id => @vital.patient_id) %> |
<%= link_to 'Back', patient_path(@vital.patient_id) %>