config/routes.rb
Md::Application.routes.draw do

  resources :dashboards

  

  devise_for :users

  match "/patients/search", :controller => "patients", :action => "search", :via => :get

  resources :patients do
    match 'timeline' => "patients#timeline", :action => 'timeline', :via => :get
    get :autocomplete_patients_last_name, :on => :collection

    resources :allergies do
      get :autocomplete_allergies_name, :on => :collection
      resources :attachments
    end
    resources :immunizations do
      get :autocomplete_immunizations_name, :on => :collection
      resources :attachments
    end
    resources :surgeries do
      get :autocomplete_surgeries_name, :on => :collection
      resources :attachments
    end
    resources :imagings do
      get :autocomplete_imagings_name, :on => :collection
      resources :attachments
    end
    resources :medications do
      get :autocomplete_medications_name, :on => :collection
      get :autocomplete_medications_med_type, :on => :collection
      get :autocomplete_medications_dose_unit, :on => :collection
      resources :attachments
    end
    resources :vitals do
      get :autocomplete_vitals_name, :on => :collection
      get :autocomplete_vitals_vital_unit, :on => :collection
      resources :attachments 
    end

  end

  match "/uploads/:id/:filename.:extension", :controller => "attachments", :action => "download", :constraints => { :filename => /[^\/]+/ },  :conditions => { :method => :get }

  root :to => 'dashboards#index'

end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :patient

  has_many :attachments, :dependent => :destroy

  accepts_nested_attributes_for :attachments, :reject_if => lambda { |c| c[:attachment].blank? }

end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController

  before_filter :authenticate_user!
  # autocomplete :allergies, :name, :class_name => Allergy

  def autocomplete_allergies_name
    term = params[:term]
    if term && !term.empty?
        items = Allergy.select("distinct name").
            where("LOWER(name) like ?", '%'+term.downcase + '%').
            limit(10).order(:name)
     else
       items = {}
     end
     render :json => json_for_autocomplete(items, :name)
  end
  
  # GET /allergies
  # GET /allergies.json
  def index
    @patient = Patient.find(params[:patient_id])
    @allergies = Allergy.find_all_by_patient_id(params[:patient_id])

    @page_title = @patient.full_name
    @page_desc = "Viewing allergies"
    
    #raise @allergies.select{|a| !a.patient}.inspect
    if can? :manage, @patient
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @allergies }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # GET /allergies/1
  # GET /allergies/1.json
  def show
    @patient = Patient.find(params[:patient_id])
    @allergy = @patient.allergies.find(params[:id])

    @page_title = @patient.full_name
    @page_desc = "Viewing allergy"

    if can? :manage, @patient
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @allergy }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # GET /allergies/new
  # GET /allergies/new.json
  def new
    @patient = Patient.find(params[:patient_id])
    @allergy = @patient.allergies.new
    # @attachment = @allergy.attachments.new

    @page_title = @patient.full_name
    @page_desc = "Adding a new allergy"

    if can? :manage, @patient
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @allergy }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # GET /allergies/1/edit
  def edit
    # @allergy = Allergy.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @allergy = @patient.allergies.find(params[:id])

    @page_title = @patient.full_name
    @page_desc = "Editing an allergy"

    if can? :manage, @patient
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # POST /allergies
  # POST /allergies.json
  def create
    #@allergy = Allergy.new(params[:allergy])
    # @allergy = Patient.find(params[:patient_id]).allergies.build(params[:allergy])
    @patient = Patient.find(params[:patient_id])
    @allergy = @patient.allergies.build(params[:allergy])
    # if @allergy = @patient.allergies.create(params[:allergy])
    #   # success
    # else
    #   # error handling
    # end

    if can? :manage, @patient
      respond_to do |format|
        if @allergy.save
          format.html { redirect_to patient_allergies_url(params[:patient_id]), notice: 'Allergy was successfully created.' }
          format.json { render json: @allergy, status: :created, location: @allergy }
        else
          format.html { render action: "new" }
          format.json { render json: @allergy.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # PUT /allergies/1
  # PUT /allergies/1.json
  def update
    #@allergy = Allergy.find(params[:id])
    #@allergy = Patient.find(params[:patient_id]).allergies.build(params[:allergy])
    @patient = Patient.find(params[:patient_id])
    @allergy = @patient.allergies.find(params[:id])

    if can? :manage, @patient
      respond_to do |format|
        if @allergy.update_attributes(params[:allergy])
          # format.html { redirect_to @allergy, notice: 'Allergy was successfully updated.' }
          format.html { redirect_to patient_allergies_url(params[:patient_id]), notice: 'Allergy was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @allergy.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end

  # DELETE /allergies/1
  # DELETE /allergies/1.json
  def destroy
    # @allergy = Allergy.find(params[:id])
    @patient = Patient.find(params[:patient_id])
    @allergy = @patient.allergies.find(params[:id])
    if can? :manage, @patient
      @allergy.destroy

      respond_to do |format|
        format.html { redirect_to patient_allergies_url(params[:patient_id]), notice: 'Allergy was successfully deleted.' }
        format.json { head :ok }
      end
    else
      redirect_to patients_url, :notice => 'You are not allowed to view this Patient'
    end
  end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/views/allergies/_fields.html.erb
<fieldset>
  <legend><%= @page_desc %></legend>
  <% if @allergy.errors.any? %>
    <div id="error_explanation">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
       <b><%= pluralize(@allergy.errors.count, "error") %> prohibited this allergy from being saved:</b>

      <ul>
      <% @allergy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class=>'control-label' %>
    <div class="controls">
      <%= f.autocomplete_field :name, autocomplete_allergies_name_patient_allergies_path, :class => 'xlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :desc, :class=>'control-label' %>
    <div class="controls">
      <%= f.text_area :desc, :class=> 'xlarge',  :rows => '4' %>
    </div>
  </div>

  <%= f.fields_for :attachments do |attachment_form|  %>
  <div class="control-group">
    <%= attachment_form.label :attachment, :class=>'control-label' %>
    <div class="controls">
      <%= attachment_form.file_field :attachment %>
      <%= attachment_form.link_to_remove "Remove this attachment" %>
    </div>
  </div>
  <% end %> 
  
  <%= f.link_to_add "Add attachment", :attachments, :class=>'btn btn-mini btn-info add_attachment_link_button' %>

  <div class="actions form-actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
</fieldset> 

app/views/allergies/_form.html.erb
<%= form_for([@allergy, @attachment], :url => patient_allergy_path) do |f| %>
  <% if @allergy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allergy.errors.count, "error") %> prohibited this allergy from being saved:</h2>
      <ul>
      <% @allergy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/allergies/edit.html.erb
<%= nested_form_for [@patient, @allergy], :html => {:multipart => true, :class=>'form-horizontal'} do |f| %> 
    <%= render :partial => "fields", :locals => {:f => f} %>
<% end %>

app/views/allergies/index.html.erb
<table class="table table-striped table-bordered">
  <% if @allergies.empty? %>
  <tr>
    <td>
      <span id="no_record">No record.</span>
    </td>
  </tr>
  <% end %>

  <% @allergies.each do |allergy| %>
    <tr>
      <td>
        <h3><%= allergy.name %></h3>
        <i><%= allergy.desc %></i>

        <% if allergy.attachments.length > 0 %>
          <ul class="attachments_list">
          <% allergy.attachments.each do |attachment| %>
            <li>
              <% if FileTest.exists?(attachment.attachment.thumb_100x100.url) %>
                <a href="/uploads/<%= attachment.id %>/<%= File.basename(attachment.attachment.url) %>"><img src="/uploads/<%= attachment.id %>/<%= File.basename(attachment.attachment.thumb_100x100.url) %>"/></a>
                  
              <% else %>
                 <a href="/uploads/<%= attachment.id %>/<%= File.basename(attachment.attachment.url) %>"><%= File.basename(attachment.attachment.url) %></a>
              <% end %>
              <br/>
              <%= link_to 'Delete', patient_allergy_attachment_path(allergy.patient_id, allergy, attachment), :class => 'btn btn-mini',confirm: 'Are you sure you want to delete "'+File.basename(attachment.attachment.url) +'" ?', method: :delete %>
            </li>
          <% end %> 
          </ul>
        <% end %> 
      </td>
      <td>
        <%= link_to 'Edit', edit_patient_allergy_path(allergy.patient_id, allergy), :class => 'btn btn-info btn-mini' %> 
        <%= link_to 'Remove', patient_allergy_path(allergy.patient_id, allergy), :class => 'btn btn-danger btn-mini',confirm: 'Are you sure?', method: :delete %>
        <%= link_to 'Add Attachment', new_patient_allergy_attachment_path(allergy.patient_id, allergy.id), :class => 'btn btn-success btn-mini' %>
      </td>
    </td>
    </tr>
    
    <tr>
      <td colspan="2">
        &nbsp;
      </td>
    </tr>
  <% end %>
</table>
<br />

<%= link_to 'New Allergy', new_patient_allergy_path %>

app/views/allergies/new.html.erb
<%= nested_form_for [@patient, @allergy], :html => {:multipart => true,  :class=>'form-horizontal'} do |f| %> 
    <%= render :partial => "fields", :locals => {:f => f} %>
<% end %>

app/views/allergies/show.html.erb
<p>
  <b>Name:</b>
  <%= @allergy.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @allergy.desc %>
</p>

<p>
  <b>Patient:</b>
  <%= @allergy.patient.full_name %>
</p>

<%= link_to 'Edit', edit_patient_allergy_path(@allergy, :patient_id => @allergy.patient_id) %> |
<%= link_to 'Back', patient_path(@allergy.patient_id) %>