config/routes.rb
Md::Application.routes.draw do

  resources :dashboards

  

  devise_for :users

  match "/patients/search", :controller => "patients", :action => "search", :via => :get

  resources :patients do
    match 'timeline' => "patients#timeline", :action => 'timeline', :via => :get
    get :autocomplete_patients_last_name, :on => :collection

    resources :allergies do
      get :autocomplete_allergies_name, :on => :collection
      resources :attachments
    end
    resources :immunizations do
      get :autocomplete_immunizations_name, :on => :collection
      resources :attachments
    end
    resources :surgeries do
      get :autocomplete_surgeries_name, :on => :collection
      resources :attachments
    end
    resources :imagings do
      get :autocomplete_imagings_name, :on => :collection
      resources :attachments
    end
    resources :medications do
      get :autocomplete_medications_name, :on => :collection
      get :autocomplete_medications_med_type, :on => :collection
      get :autocomplete_medications_dose_unit, :on => :collection
      resources :attachments
    end
    resources :vitals do
      get :autocomplete_vitals_name, :on => :collection
      get :autocomplete_vitals_vital_unit, :on => :collection
      resources :attachments 
    end

  end

  match "/uploads/:id/:filename.:extension", :controller => "attachments", :action => "download", :constraints => { :filename => /[^\/]+/ },  :conditions => { :method => :get }

  root :to => 'dashboards#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user.role == 'admin'
      can :manage, :all
    end

    #owners can manage their own patient record
    can :manage, Patient, :user_id => user.id
    can :manage, Dashboard, :user_id => user.id
  end
end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :patient

  has_many :attachments, :dependent => :destroy

  accepts_nested_attributes_for :attachments, :reject_if => lambda { |c| c[:attachment].blank? }

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible  :desc, :attachment, :allergy_id, :immunization_id, :imaging_id, :medication_id, :vital_id

  belongs_to :immunization
  belongs_to :allergy
  belongs_to :surgery
  belongs_to :imaging
  belongs_to :medication
  belongs_to :vital
  
  validates :attachment, :presence => true

  mount_uploader :attachment, AttachmentUploader
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/imaging.rb
class Imaging < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :patient
  has_many :attachments, :dependent => :destroy

  accepts_nested_attributes_for :attachments, :reject_if => lambda { |c| c[:attachment].blank? }

  validate :taken_on_is_date
  private

  def taken_on_is_date
    if !taken_on.is_a?(Date)
      errors.add(:taken_on, 'must be a valid date')   
    end
  end
end

app/models/immunization.rb
class Immunization < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :patient
  has_many :attachments, :dependent => :destroy

  accepts_nested_attributes_for :attachments, :reject_if => lambda { |c| c[:attachment].blank? }

  validate :immunized_on_is_date
  private

  def immunized_on_is_date
    if !immunized_on.is_a?(Date)
      errors.add(:immunized_on, 'must be a valid date')   
    end
  end
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :patient
  has_many :attachments, :dependent => :destroy
  validates :dose, :numericality => true

  accepts_nested_attributes_for :attachments, :reject_if => lambda { |c| c[:attachment].blank? }
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates :first_name, :last_name, :dob, :presence => true
  has_many :allergies, :dependent => :destroy
  has_many :immunizations, :dependent => :destroy
  has_many :surgeries, :dependent => :destroy
  has_many :imagings, :dependent => :destroy
  has_many :medications, :dependent => :destroy
  has_many :vitals, :dependent => :destroy
  belongs_to :user

  
  def age
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def full_name
    first_name + " " + last_name
    
  end
end

app/models/surgery.rb
class Surgery < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :patient
  has_many :attachments, :dependent => :destroy
  
  accepts_nested_attributes_for :attachments, :reject_if => lambda { |c| c[:attachment].blank? }

  validate :operated_on_is_date
  private

  def operated_on_is_date
    if !operated_on.is_a?(Date)
      errors.add(:operated_on, 'must be a valid date')   
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :patients

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  validates :email, :password, :presence => true

  after_initialize :init

  def init
  	self.role ||= 'user' #will set a default value only if it's nil
  end
end

app/models/vital.rb
class Vital < ActiveRecord::Base
  validate :vital_date_is_date
  validates :name, :presence => true
  validates :vital_value, :numericality => true
  belongs_to :patient
  has_many :attachments, :dependent => :destroy

  accepts_nested_attributes_for :attachments,:reject_if => lambda { |c| c[:attachment].blank? }

  # scope :unique_name, group(:name)
  # scope :unique_vital_unit, group(:vital_unit)

  private

  def vital_date_is_date
    # Rails.logger.info ("EEEEEEEEEEEEEEEEE "+vital_date.to_yaml)
    if !vital_date.is_a?(Date)
      errors.add(:vital_date, 'must be a valid date')
    end

  end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/imagings_helper.rb
module ImagingsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
  def age(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
end

app/helpers/surgeries_helper.rb
module SurgeriesHelper
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Md</title>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "bootstrap" %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container" style="padding-top: 0px;">

<!-- Topbar
    ================================================== -->
<div class="row">
  <div class="span12 top-text">
    <% if user_signed_in? %>
      Hi <em><%= current_user.email %></em>!
      <%= link_to 'Edit Password', edit_user_registration_path %>
      <i class="icon-off"></i> <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    <% else %>
      <!-- <%= link_to 'Sign In', new_user_session_path%> -->
    <% end %>
  </div>
</div>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Medical Directory App</a>
      <div class="nav-collapse">
      <% if user_signed_in? %>
        
          <ul class="nav">
            <li><%= link_to 'Dashboard', root_path %></li>
            <li><%= link_to 'Patient List', patients_path %></li>
            <li><%= link_to 'New Patient', new_patient_path %></li>
            <li><%= link_to 'Reports', root_path %></li>
          </ul>
          <form class="navbar-search pull-left">
            <%= autocomplete_field 'search','full_name', autocomplete_patients_last_name_patients_path,  :class=>"search-query", :placeholder=>"Search"%>
          </form>
      <% end %>
      </div>
      </div>
    </div>
</div>  
  <div class="content">
    <% if defined? @page_title %>
      <div class="page-header">
        <h2><%= @page_title || "" %> <small><%= @page_desc || "" %></small></h2>
      </div>
    <% end %>
    <div class="row">
      <div class="span12">
        <% if flash[:alert] %>
          <div class="alert alert-error">
            <%= flash[:alert] %>
          </div>
        <% end %>
        <% if flash[:notice] %>
          <div class="alert alert-info">
            <%= flash[:notice] %>
          </div>
        <% end %>
      </div>
    </div>
    
    <% if defined? @patient %> 
      <% if @patient.id? %>
        
        <div class="row">
          <div class="span12">

            <ul class="nav nav-pills">
              <li class="<%= controller.controller_name == 'patients' && controller.action_name == 'show' ? ' active ' : '' %>"><%= link_to 'Profile', @patient %>
              </li>

              <li class="<%= controller.controller_name == 'patients' && controller.action_name == 'timeline' ? ' active ' : '' %>"><%= link_to 'Timeline', patient_timeline_path(@patient)%> 
              </li>

              <li id="vitals" class="dropdown <%= controller.controller_name == 'vitals' ? ' active ' : '' %>">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#vitals">
                  Vitals
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="<%= controller.controller_name == 'vitals' && controller.action_name == 'index' ? ' active ' : '' %>">
                    <%= link_to 'View', patient_vitals_path(@patient.id) %>
                  </li>
                  <li class="<%= controller.controller_name == 'vitals' && controller.action_name == 'new' ? ' active ' : '' %>">
                    <%= link_to 'Add', new_patient_vital_path(@patient.id) %>
                  </li>
                </ul>
              </li>

              <li class="dropdown <%= controller.controller_name == 'allergies'  ? ' active ' : '' %>"><a class="dropdown-toggle" data-toggle="dropdown" href="#allergies">
                  Allergies
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="<%= controller.controller_name == 'allergies' && controller.action_name == 'index' ? ' active ' : '' %>">
                    <%= link_to 'View', patient_allergies_path(@patient.id) %>
                  </li>
                  <li class="<%= controller.controller_name == 'allergies' && controller.action_name == 'new' ? ' active ' : '' %>">
                    <%= link_to 'Add', new_patient_allergy_path(@patient.id) %>
                  </li>
                </ul>
              </li>

              <li class="dropdown <%= controller.controller_name == 'immunizations' ? ' active ' : '' %>"><a class="dropdown-toggle" data-toggle="dropdown" href="#immunizations">
                  Immunizations
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="<%= controller.controller_name == 'immunizations' && controller.action_name == 'index' ? ' active ' : '' %>">
                    <%= link_to 'View', patient_immunizations_path(@patient.id) %>
                  </li>
                  <li class="<%= controller.controller_name == 'immunizations' && controller.action_name == 'new' ? ' active ' : '' %>">
                    <%= link_to 'Add', new_patient_immunization_path(@patient.id) %>
                  </li>
                </ul>
              </li>

             <li class="dropdown <%= controller.controller_name == 'surgeries' ? ' active ' : '' %>"><a class="dropdown-toggle" data-toggle="dropdown" href="#surgeries">
                  Surgeries
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="<%= controller.controller_name == 'surgeries' && controller.action_name == 'index' ? ' active ' : '' %>">
                    <%= link_to 'View', patient_surgeries_path(@patient.id) %>
                  </li>
                  <li class="<%= controller.controller_name == 'surgeries' && controller.action_name == 'new' ? ' active ' : '' %>">
                    <%= link_to 'Add', new_patient_surgery_path(@patient.id) %>
                  </li>
                </ul>
              </li>

              <li class="dropdown <%= controller.controller_name == 'imagings' ? ' active ' : '' %>"><a class="dropdown-toggle" data-toggle="dropdown" href="#imagings">
                  Imagings
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="<%= controller.controller_name == 'imagings' && controller.action_name == 'index' ? ' active ' : '' %>">
                    <%= link_to 'View', patient_imagings_path(@patient.id) %>
                  </li>
                  <li class="<%= controller.controller_name == 'imagings' && controller.action_name == 'new' ? ' active ' : '' %>">
                    <%= link_to 'Add', new_patient_imaging_path(@patient.id) %>
                  </li>
                </ul>
              </li>

              <li class="dropdown <%= controller.controller_name == 'medications' ? ' active ' : '' %>"><a class="dropdown-toggle" data-toggle="dropdown" href="#medications">
                  Medications
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="<%= controller.controller_name == 'medications' && controller.action_name == 'index' ? ' active ' : '' %>">
                    <%= link_to 'View', patient_medications_path(@patient.id) %>
                  </li>
                  <li class="<%= controller.controller_name == 'medications' && controller.action_name == 'new' ? ' active ' : '' %>">
                    <%= link_to 'Add', new_patient_medication_path(@patient.id) %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>  
        </div>  
      <% end %>
    <% end %>
  
    <div class="row">
      <div class="span12">
        <%= yield %>
      </div>
    </div>

    <div class="row">
      <footer class="span12" style="text-align: center;">
      <p>&copy; Copyright 2012 - Wenbert Del Rosario</p>
        <p class="pull-right"><a href="#">Back to top</a></p>
        
      </footer>
    </div>
  </div>
</div> <!-- /container -->
</body>
</html>